# Generated by Django 2.0.6 on 2019-09-26 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190924_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=90)),
                ('textoTitulo', models.CharField(max_length=80)),
                ('preco', models.IntegerField()),
                ('textoAnuncio', models.CharField(max_length=150)),
                ('nomeContato', models.CharField(max_length=60)),
                ('telefone', models.CharField(max_length=20)),
                ('secao', models.CharField(max_length=25)),
                ('tipoAnuncio', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Apartamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('qtdQuartoss', models.IntegerField()),
                ('proprietario', models.CharField(max_length=80)),
                ('valorCondominio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('descricaoProduto', models.CharField(max_length=95)),
                ('qtdPrevistoMes', models.FloatField()),
                ('preco', models.FloatField()),
                ('precoMaximo', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('telefone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.CharField(max_length=35)),
                ('tipo_despesa', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=60)),
                ('forma_pagamento', models.CharField(max_length=40)),
                ('vencimento', models.DateField()),
                ('quitado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Livraria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=105)),
                ('Nome_do_autor', models.CharField(max_length=70)),
                ('Assunto', models.CharField(max_length=50)),
                ('Editora', models.CharField(max_length=50)),
                ('ISBN', models.CharField(max_length=50)),
                ('Publicacao', models.DateField()),
            ],
        ),
    ]
